version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-fpm-app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "9000:9000"
    depends_on:
      - db
  
  nginx:
    image: nginx:latest
    container_name: nginx-laravel
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app


  db:
    image: postgres:latest
    container_name: pgsql-db
    environment:
      POSTGRES_USER: teste
      POSTGRES_PASSWORD: teste#@
      POSTGRES_DB: teste
    volumes:
      - ./docker/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
    driver: local
